---
title: "Interests in Emerging Chemicals"
description: "How to evaluate risk when chemical data is sparse?    \n"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Overview
Modern economies consume (and produce) tens of thousands of chemicals. In some countries, regulators would like to assess each new chemical before it enters into its nominated use. This could require laboratory testing to determine chemical properties, such as persistence and toxicity. Ideally, regulators would be able to anticipate "emerging chemicals" which will adverse effects on human and environmental health (more concisely, AEs), and impose appropriate regulatory actions. <br>

However, as the case of PFAS (per- and poly-fluoroalkyl substances) shows, regulators may not have the resources to collect data on all chemicals. Further, a regulator's resources may be further stretched by having to consider chemical interactions, or the need to re-assess chemicals as their usage changes, or new information becomes available. <br>

As a result of limited resources and insufficient chemical data, chemicals can enter into widespread use, causing AEs, community concern, and a reduction in the public's confidence in regulators. <br> 

My approach is to consider whether published scientific literature can provide clues on which chemicals are showing a pattern of proceeding towards requiring regulatory action. By recognising such "chemicals of interest", a regulator may focus its limited resources on testing a relatively small number of chemicals. The intent is to recognise AE-causing chemicals more quickly, allowing a regulator to apply management in a more timely manner. 

#### Recent publications or reports on emerging chemicals
 Whyte, J. M., **“Project 1: Predicting the Emergence of ‘Chemicals of Interest’ via the Study of Scientific Publications”**, Centre for Environmental and Economic Research report for NSW Environment Protection Authority, January 2021. <br>
 **Abstract**: _Modern economies employ a large volume and variety of chemicals. Yet, regulators typically have limited resources for conducting risk assessments. Further, the laboratory data available for chemical assessments is often insufficient. Consequently, chemicals in various jurisdictions (such as the per- and poly-fluoroalkyl substances, PFAS) have entered into widespread use, at which point Adverse Effects (AEs, including environmental impacts and health risks) are recognised. A regulator must then 'reactively' manage chemical risks and impacts. This report develops an approach to assisting a regulator’s task of anticipating risks due to ‘emerging contaminants’ that does not depend on chemical data. Instead, we propose to detect risks by considering the ‘research interest’ relating to individual chemicals and their AEs in a database of scientific publications (Web of Science) across a time interval. We consider a range of chemicals, some regulated, and some unregulated. We hypothesise that the research interest into regulated chemicals will have features that are absent from the research interest of unregulated chemicals. Then, by learning these features, we can use them in a classification process able to distinguish those chemicals likely to require regulation from others. Such information would allow a regulator to focus its limited resources on assessing a smaller number of chemicals than previously. Ultimately, this should lead to an earlier recognition of chemical AEs, and hence, more timely regulation of these. This action should reduce harm to human and environmental health, and disruption to industry. Following data exploration and the development of our method with reference to a training data set, our classification results on a validation set are promising. We note avenues for refinement of our data mining and time-series classification methods that should lead to improved results._
 <a href="Project1_NSW_EPA_report.pdf">Download File</a>
 
 Whyte, J. M., **"On Using ‘Emerging Interest’ in Scientific Literature to Inform Chemical Risk Prioritisation"**, accepted, to appear in the proceedings of the 10th International Environmental Modelling and Software Society Congress, Sept 14-18 2020, Brussels, Belgium. [Pre-publication, post-review version here](https://www.researchgate.net/publication/344293743_On_Using_'Emerging_Interest'_in_Scientific_Literature_to_Inform_Chemical_Risk_Prioritisation). <br>
**Summary:** This conference paper laid the groundwork for the Project 1 report above. The results showed that my approach could anticipate chemicals of concern earlier than a regulator could. This result has encouraged further research in this area. 

 Whyte, J. M. and Robinson, A. P., **“Outcome 2: Automating the extraction of chemical prevalences from a bibliographic database to estimate ‘emerging concern’ — a pilot study”**, CEBRA report for NSW Environment Protection Authority, January 2020. <br>
**Summary**: The New South Wales Environment Protection Authority (NSW EPA) is overseeing the development of a Chemical Prioritisation Framework (CPF) that intends to direct regulatory attention to potential risks to human and animal welfare. The framework requires the “emerging concern” associated with candidate chemicals as an input. Initially the emerging concern associated with a given chemical was derived from the number of publications in the Taylor and Francis online portal referring to that chemical over a calendar year ("hits"), for a period of years. This limited the search for hits to those by only one publisher, and hit counts were drawn manually. <br>
In this pilot study we consider some extensions and refinements. We investigated these in a systematic manner that is reproducible and largely automated. We achieved this by using R code to obtain hit counts over calendar years from the Web of Science core collection API (henceforth, WOS).

Our methodology can:

<ul>
<li>recognise certain trends in scientific publication data, and,</li>
<li>discern a point in time at which there is a sharp increase in the attention given by the scientific literature to the harmful effects of a chemical—the type of event one could associate with “emerging concern”.</li>
</ul>
We also intended to associate chemicals with mentions of major NSW population centres in WoS, however data was scant.
<a href="NSW_EPA_Outcome2_report.pdf">Download File</a>

Significantly, this study stimulated ideas that were profitably explored in "On Using 'Emerging Interest' in Scientific Literature to Inform Chemical Risk Prioritisation", listed above. 





 
#### Work in progress
Whyte, J. M., **"Exploiting scientific publication trends for chemical risk management"** <br>
This paper will consider features of publication keywords over time. I will likely present some
preliminary results at the "Early Career & Studenet Statisticians Conference", July 26 -- August 1st 2021.

#### Recent talks on emerging chemicals
**“On Using ‘Emerging Interest’ in Scientific Publications to Inform Chemical Risk Prioritisation (with updates)”**, invited oral presentation, The Australian Laboratory for Emerging Contaminants’ “Emerging Contaminants Workshop” (School of Chemistry, University of Melbourne, online), Oct 27th 2020.
