---
title: "Streaks of Synthesis"
description: |
  The (developing) website of Jason M. Whyte, PhD. <br> 
  
  I'm an Australian applied mathematician with varied analytical and computational interests, driven by applications.^[I also quite like footnotes.] <br>
  
  <span style="color:blue;"> Why 'Synthesis'? </span> I'm an inter-disciplinary researcher, always on the look out for good ideas from other fields. <br> 
  
  My projects have led to new methodologies and software. 
  
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

<span style="color:blue;"> Click a tab in the top-right for details of my interests and activities. </span>

<!-- # I broadly divide my interdisciplinary interests into three areas. -->
  
<!-- # <span style="color:blue;">"Environmental Data Science":</span> In recent work^[Centre for Environmental and Economic Research, University of Melbourne] I've considered the emergence of chemicals adversely affecting humans or the environment. I've used web-scraping, text mining, dynamic networks, and time series analysis in attempting to anticipate such emergence. -->
  
<!-- # <span style="color:blue;">"Health and Statistics:"</span> Modelling to understand disease progression. -->

## My main research interests include^[sometimes unpopular] aspects of: <br>
 
### Mathematical Biology

**Biological modelling:** I've considered biochemical systems and human biomarker concentration time series.<br>
The broad question here is: <br>
<span style="color: blue;"> _Ιf we can propose a model structure (collection of related models) to represent a physical system, can we control the system, or predict its behaviour?_ <span style="color: blue;">

[**Model structure analysis:**](http://127.0.0.1:40279/rmd_output/4/MathBio.html#structural-global-identifiability-sgi-problems) success in modelling may be determined by the nature of the model structure we use. More data and better quality data may not remedy a study destined to fail due to undesirable model properties. <br>
<span style="color: blue;"> _If estimation of model parameters leads to multiple values that are equally feasible, what does this mean?_ </span>  <br>
(Hint: problems with reproducibility of results are possible. If alternative parameter estimates lead the model structure to produce dissimilar predictions, we cannot predict system behaviour with confidence.)
However, we can anticipate this type of problem prior to data collection through interrogating the assumed model structure.

### [Emerging Chemical Pollutants](http://127.0.0.1:40279/rmd_output/4/EmergingChems.html)
We could call these projects^[at the Centre for Environmental and Economic Research, University of Melbourne] "Environmental Data Science". Consider the PFAS (per- and poly-fluoroalkyl substances), which entered into widespread use. Some of these chemicals were then found to have adverse effects on human and environmental health. Regulators must now reactively manage this problem. <br>
<span style="color: blue;"> _How can mathematics and statistics give regulators advance warning of tomorrow's nightmares?_ </span> <br>
To gain a sense of the scale of the problem with PFAS "forever chemicals": [see this investigation by Tom Perkins, published in The Guardian](https://www.theguardian.com/us-news/2021/feb/23/pfas-testing-forever-chemicals-household-water-cat) on February 24th 2021.

  